#!/usr/bin/python -tt
# jsonaddress - urwid-based JSON address book editor
#
# Copyright (c) 2010, Rob Lanphier
# All rights reserved.
# Licensed under BSD-style license.  See LICENSE.txt for details.

import optparse
import sys
import jsonwidget

def main():
    '''standard option parsing stuff'''
    usage = "usage: %prog [options] arg"
    parser = optparse.OptionParser(usage)
    (options, args) = parser.parse_args()

    if len(args) > 1:
        parser.error("Too many arguments." +
                     "  Just one adddressbook file at a time, please.")
    if len(args) == 1:
        addressbook = args[0]
    else:
        addressbook = None
    jsonwidget.run_editor(addressbook, 
                          schemafile="schema/addressbookschema.json",
                          program_name="jsonaddress 0.1")

if __name__ == "__main__":
    main()

