#!/usr/bin/python -tt
# jsonaddress - urwid-based JSON address book editor
#
# Copyright (c) 2010, Rob Lanphier
# All rights reserved.
# Licensed under BSD-style license.  See LICENSE.txt for details.

import jsonwidget.commands

jsonwidget.commands.jsonaddress()

