#!/usr/bin/python -tt
# jsonedit - urwid-based JSON editor
#
# Copyright (c) 2010, Rob Lanphier
# All rights reserved.
# Licensed under BSD-style license.  See LICENSE.txt for details.

import json
import urwid.curses_display
import urwid
import optparse
import sys
import os

from jsonwidget.termedit import *

# Force monochrome for now.  Will probably revisit when 0.9.9 is widely
# deployed
urwid.curses_display.curses.has_colors = lambda: False


def show_form(schemafile, jsonfile):
    form = JsonEditor(jsonfile=jsonfile, schemafile=schemafile,
                      program_name="jsonedit 0.1pre")
    form.run()


def main():
    '''standard option parsing stuff'''
    usage = "usage: %prog [options] arg"
    parser = optparse.OptionParser(usage)
    parser.add_option("-s", "--schema", dest="schema",
                      default="schema/datatype-example-schema.json",
                      help="use this schema to build the form")
    parser.add_option("--tracebacks", dest="tracebacks",
                      default=False,
                      help="See full tracebacks")
    (options, args) = parser.parse_args()
    if not options.tracebacks:
        sys.tracebacklimit = 1000

    if len(args) > 1:
        parser.error("Too many arguments." +
                     "  Just one .json file at a time, please.")
    if len(args) == 1:
        jsonfile = args[0]
    else:
        jsonfile = None
    show_form(options.schema, jsonfile)

if __name__ == "__main__":
    main()

